// ============================================
// MOCK DATA — generic robot mower brands & models
// ============================================

const ROBOTS = [
  {
    id: 'verdura-x9',
    brand: 'Verdura',
    model: 'X9 Pro',
    fullName: 'Verdura X9 Pro',
    tagline: 'L\'expert toutes surfaces',
    surface: 2500,
    slope: 45,
    price: 1899,
    oldPrice: 2199,
    rating: 4.8,
    reviewCount: 247,
    badge: 'NOTRE CHOIX',
    color: '#3a5a3d',
    pros: ['Sans fil périphérique', 'Gère 45% de pente', 'IA d\'évitement avancée', 'Garantie 5 ans'],
    cons: ['Prix élevé', 'Application perfectible'],
    specs: { weight: '13kg', noise: '58dB', battery: '180min', charging: '90min', cutHeight: '20-60mm', cuttingWidth: '24cm' },
    score: { ease: 9.2, performance: 9.5, durability: 9.0, value: 8.4, app: 8.1 },
    vendors: [
      { name: 'Amazon', price: 1899, oldPrice: 2199, primary: true },
      { name: 'Leroy Merlin', price: 1949 },
      { name: 'Boulanger', price: 1999 },
    ],
  },
  {
    id: 'ecomower-580',
    brand: 'EcoMower',
    model: 'Volta 580',
    fullName: 'EcoMower Volta 580',
    tagline: 'Le meilleur rapport qualité-prix',
    surface: 800,
    slope: 30,
    price: 749,
    oldPrice: 899,
    rating: 4.6,
    reviewCount: 1892,
    badge: 'MEILLEUR PRIX',
    color: '#b8623d',
    pros: ['Excellent prix', 'Installation rapide', 'Très silencieux (54dB)', 'Pluie OK'],
    cons: ['Limité à 800m²', 'Pas de GPS'],
    specs: { weight: '8.5kg', noise: '54dB', battery: '90min', charging: '60min', cutHeight: '20-50mm', cuttingWidth: '17cm' },
    score: { ease: 8.8, performance: 8.2, durability: 8.5, value: 9.6, app: 7.8 },
    vendors: [
      { name: 'Amazon', price: 749, oldPrice: 899, primary: true },
      { name: 'Cdiscount', price: 779 },
      { name: 'Manomano', price: 799 },
    ],
  },
  {
    id: 'greenbot-go',
    brand: 'GreenBot',
    model: 'Go 1500',
    fullName: 'GreenBot Go 1500',
    tagline: 'Polyvalent et fiable',
    surface: 1500,
    slope: 35,
    price: 1199,
    rating: 4.5,
    reviewCount: 634,
    color: '#243b2a',
    pros: ['Bonne autonomie', 'Multi-zones (4)', 'Capteurs pluie & gel', 'Bon SAV'],
    cons: ['Bruit moyen', 'Câble périphérique requis'],
    specs: { weight: '11kg', noise: '60dB', battery: '120min', charging: '70min', cutHeight: '25-65mm', cuttingWidth: '22cm' },
    score: { ease: 8.4, performance: 8.7, durability: 8.9, value: 8.6, app: 8.3 },
    vendors: [
      { name: 'Amazon', price: 1199, primary: true },
      { name: 'Castorama', price: 1249 },
      { name: 'Bricomarché', price: 1279 },
    ],
  },
  {
    id: 'terracut-t5',
    brand: 'TerraCut',
    model: 'T5 Connect',
    fullName: 'TerraCut T5 Connect',
    tagline: 'Le plus connecté',
    surface: 1200,
    slope: 40,
    price: 1349,
    rating: 4.4,
    reviewCount: 412,
    badge: 'PLUS CONNECTÉ',
    color: '#8ba88e',
    pros: ['App très complète', 'Caméra HD intégrée', 'Détection animaux', 'Mises à jour OTA'],
    cons: ['Setup complexe', 'Batterie moyenne'],
    specs: { weight: '12kg', noise: '62dB', battery: '100min', charging: '75min', cutHeight: '20-55mm', cuttingWidth: '20cm' },
    score: { ease: 7.8, performance: 8.5, durability: 8.4, value: 8.0, app: 9.7 },
    vendors: [
      { name: 'Fnac', price: 1349, primary: true },
      { name: 'Darty', price: 1379 },
      { name: 'Amazon', price: 1399 },
    ],
  },
  {
    id: 'hexamow-mini',
    brand: 'Hexamow',
    model: 'Mini 350',
    fullName: 'Hexamow Mini 350',
    tagline: 'Idéal petit jardin',
    surface: 350,
    slope: 25,
    price: 449,
    oldPrice: 549,
    rating: 4.3,
    reviewCount: 2103,
    color: '#d97742',
    pros: ['Imbattable sur petits jardins', 'Très compact', 'Plug & play', 'Économique'],
    cons: ['Limité à 350m²', 'Pas de pluie'],
    specs: { weight: '6.2kg', noise: '52dB', battery: '60min', charging: '50min', cutHeight: '20-45mm', cuttingWidth: '15cm' },
    score: { ease: 9.5, performance: 7.5, durability: 7.8, value: 9.2, app: 7.2 },
    vendors: [
      { name: 'Amazon', price: 449, oldPrice: 549, primary: true },
      { name: 'Manomano', price: 469 },
    ],
  },
  {
    id: 'verdura-titan',
    brand: 'Verdura',
    model: 'Titan 5000',
    fullName: 'Verdura Titan 5000',
    tagline: 'Pour les très grands terrains',
    surface: 5000,
    slope: 50,
    price: 3499,
    rating: 4.7,
    reviewCount: 89,
    badge: 'GRAND TERRAIN',
    color: '#1a2e1f',
    pros: ['Jusqu\'à 5000m²', 'Pente 50%', 'Lame 28cm', 'GPS RTK précis'],
    cons: ['Investissement', 'Lourd à manipuler'],
    specs: { weight: '18kg', noise: '63dB', battery: '240min', charging: '120min', cutHeight: '25-70mm', cuttingWidth: '28cm' },
    score: { ease: 8.0, performance: 9.7, durability: 9.4, value: 7.8, app: 8.4 },
    vendors: [
      { name: 'Amazon', price: 3499, primary: true },
      { name: 'Leroy Merlin', price: 3599 },
    ],
  },
];

const BRANDS = [
  { id: 'verdura', name: 'Verdura', tagline: 'Premium suédois · Référence du marché', count: 12, color: '#1a2e1f', founded: 1991, country: '🇸🇪' },
  { id: 'ecomower', name: 'EcoMower', tagline: 'Le meilleur rapport qualité-prix', count: 8, color: '#b8623d', founded: 2003, country: '🇬🇧' },
  { id: 'greenbot', name: 'GreenBot', tagline: 'Polyvalence et fiabilité allemande', count: 14, color: '#3a5a3d', founded: 1985, country: '🇩🇪' },
  { id: 'terracut', name: 'TerraCut', tagline: 'L\'innovation connectée', count: 6, color: '#243b2a', founded: 2015, country: '🇫🇷' },
  { id: 'hexamow', name: 'Hexamow', tagline: 'Compact et accessible', count: 5, color: '#d97742', founded: 2010, country: '🇨🇳' },
  { id: 'pratina', name: 'Pratina', tagline: 'Spécialiste pro et pentes', count: 9, color: '#6b7a6c', founded: 1978, country: '🇮🇹' },
];

Object.assign(window, { ROBOTS, BRANDS });
